### ISSUE TITLE
User Testing Interview Script

### ISSUE THREAD

**Issue by vlbee** [fac-13/GP_ProjectBernadette#16]
Acceptance Criteria: 

### Script
- [x] Script for User testing interviews typed up
- [x] Any addition questions to ask? (do they used laptop, smartphone or old fashioned phone call for information searching?)

### Results

- [x] Random testers on 11/06/26
- [ ] GP volunteers TBC

**Comment by vlbee** [comment]
# User Testing Interview

## Planning

### Tasks

1. Notice and click on the Wayfinder pop up on the home page.
2. Go through the WayFinder Q&As until they reach an endpoint.
3. Go back and change one of their answers. 
4. Send a message to GP to opt in for a callback.

### Users

* 4-5 Random volunteers of varying age to test general UX and usability
* 1-2 volunteers from Grandparents Plus to test clarity of content

### Equipment

Smartphone: iphone SE


## SCRIPT

> indented text is for GP-sourced volunteers.

#### 1. Introduction

My name is ____ from a digital agency called Founders & Coders. We are building a web app for a charity called Grandparents Plus and are looking for volunteers to test it out.  It will only take a couple minutes and we don't need any personal information for you.

>My name is ____ from a digital agency called Founders & Coders. We are testing a new web app we are building for Grandparents Plus. 

Thanks for agreeing to help us out today. Just so you know, some of my team will be observing you and taking notes.

#### 2. Explanation
I’d like to show you the application first (show them home page) and then give you a few tasks to do.

It's a very free exercise so there are no right or wrong ways of doing things, this is not about you getting something wrong or right, we're just looking to learn about the application.

We want you to tell us what you're thinking. As you use it, tell us anything that comes into your mind.

#### 3. Warm Up

Here is an iphone on the GrandParents Plus home page if you just want to have a look at the home page but not click on any links. 

#### 4. Task 1 (pop up)

What do you think of that pop up?

Without clicking on it, what do you think it's directing you to? 

Can you click through to the My Wayfinder app now please.
 
#### 5. Task 2

What are you looking at now? 

What do you think you have to do next? 

Some of these questions might not be relevant to you but if you don't mind playing along, can you now click through the questions and tell me anything that comes to your mind when you are using the app? We would be appreciate knowing if something happened that was different from what you were expecting to happen.

> Can you now click through the questions and tell me anything that comes to your mind when you are using the app? We would be appreciate knowing if something happened that was different from what you were expecting to happen.


#### 6. Task 3 

Let's pretend you want to change one of your answers - can you try to do that for the first question - "Are you a grandparent"?

How did you find that?

#### 7. Task 4

Now let's imagine you are a grandparent. Could you go through the app and answer yes to every question please? 

Tell us what you think of the questions as you go along. 

What are you looking at now? 

Can you try to send us a message with the form now? (Explain name is pre-filled)


#### 8. Afterwards

How did you find using the app?

Is there anything you would change?

Were any of the questions confusing?

Was anything hard to read or hard to use?

> What do you normally use to find information online? (your smartphone, a desktop, do you prefer to call on the phone?) 

#### 9. Wrap up & thanks

Do you have any questions for me or anything you want to add?

Thank you!!!!

**Comment by tspeed90** [comment]
We're closing this issue as it relates to the prototype, but we will open a new issue regarding testing for the final product.
